Repository Carbon-Knight/carbon-knight-back-end, pull requests merged in 2021-01, with the labels that each got.

#19 Rough draft readme
  README.md
Labels: documentation

#23 New footprint mutation
  app/graphql/mutations/create_footprint_and_car_monthly_mileage.rb
  app/graphql/types/mutation_type.rb
  lib/tasks/assets.rake
  spec/requests/create_footprint_mutation_spec.rb
Labels: backend

#26 Update footprint
  app/facades/footprint_facade.rb
  app/graphql/mutations/update_car_monthly_mileage.rb
  app/graphql/types/mutation_type.rb
  spec/fixtures/vcr_cassettes/As_a_User_/can_update_their_carbon_footprint.yml
  spec/requests/graphql/update_carbon_footprint_spec.rb
Labels: backend

#28 Aggregate yearly footprint
  app/graphql/mutations/create_footprint_and_car_monthly_mileage.rb
  app/graphql/queries/fetch_user_aggregate_footprint_for_year.rb
  app/graphql/types/aggregate_footprint_for_year_type.rb
  app/graphql/types/query_type.rb
  app/graphql/types/yearly_footprint_type.rb
  app/models/footprint.rb
  db/migrate/20210112222225_change_year_to_be_integer_in_car_monthly_mileages.rb
  db/schema.rb
  spec/models/footprint_spec.rb
  spec/requests/create_footprint_mutation_spec.rb
  spec/requests/footprint_request_spec.rb
  spec/requests/graphql/aggregate_footprint_for_year_spec.rb
Labels: backend

#32 Fetch all user monthly mileages
  app/graphql/queries/fetch_all_user_car_monthly_mileages.rb
  app/graphql/types/query_type.rb
  app/models/car_monthly_mileage.rb
  spec/models/car_monthly_mileage_spec.rb
  spec/requests/footprint_request_spec.rb
  spec/requests/graphql/fetch_all_user_car_monthly_mileages_spec.rb
Labels: backend

#38 User footprints years
  Gemfile
  Gemfile.lock
  app/graphql/queries/fetch_user_footprint_years.rb
  app/graphql/types/query_type.rb
  app/graphql/types/years_type.rb
  app/models/car.rb
  app/models/car_monthly_mileage.rb
  spec/factories/car_monthly_mileages.rb
  spec/factories/cars.rb
  spec/factories/footprints.rb
  spec/models/car_monthly_mileage_spec.rb
  spec/rails_helper.rb
  spec/requests/graphql/fetch_user_footprint_years_request_spec.rb
Labels: backend

#36 Delete monthly mileage
  app/graphql/mutations/delete_car_monthly_mileage.rb
  app/graphql/types/mutation_type.rb
  spec/requests/graphql/delete_car_monthly_mileage_spec.rb
  spec/requests/graphql/update_carbon_footprint_spec.rb
Labels: backend

#41 Fixed bug where update_footprint was not saving
  app/facades/footprint_facade.rb
Labels: backend, bug
